CMP = javac
ARGS = 
all: Identity.class BasicArthm.class HelloWorld.class Calls.class Fields.class Gravity.class Extends.class
Identity.class:
	$(CMP) $(ARGS) Identity.java
BasicArthm.class:
	$(CMP) $(ARGS) BasicArthm.java
HelloWorld.class:
	$(CMP) $(ARGS) HelloWorld.java
Calls.class:
	$(CMP) $(ARGS) Calls.java
Fields.class:
	$(CMP) $(ARGS) Fields.java
Gravity.class:
	$(CMP) $(ARGS) Gravity.java
Extends.class:
	$(CMP) $(ARGS) Extends.java
