CMP = javac
ARGS = 
all: Identity.class BasicArthm.class HelloWorld.class
Identity.class:
	$(CMP) $(ARGS) Identity.java
BasicArthm.class:
	$(CMP) $(ARGS) BasicArthm.java
HelloWorld.class:
	$(CMP) $(ARGS) HelloWorld.java
